package constants

const (
	BUILDING_WOOD_CUTTER     = 0
	BUILDING_STONE_QUARRY    = 1
	BUILDING_CLAY_PIT        = 2
	BUILDING_GRAIN_FIELD     = 3
	BUILDING_BARRACKS        = 4
	BUILDING_STABLES         = 5
	BUILDING_ASSEMBLY_HALL   = 6
	BUILDING_FORGE           = 7
	BUILDING_STOREHOUSE      = 8
	BUILDING_GOLD_MINE       = 9
	BUILDING_LONGHOUSE       = 10
	BUILDING_HALL_OF_PEOPLE  = 11
	BUILDING_STONE_WALL      = 12
)