services:
  postgres:
    container_name: COTN-DB
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      TZ: "Europe/Berlin"
      PGTZ: "Europe/Berlin"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: COTN-Adminer
    restart: always
    ports:
      - 8090:8080

volumes:
  postgres:

name: COTN
